---
- hosts: all
  tasks:
    - lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ansible-srv-usr ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'