---
- hosts: all
  become: true
  tasks:
    - lineinfile:
        path: /etc/sudoers
        state: present
        insertafter: '^#includedir /etc/sudoers.d'
        line: 'ansible-srv-usr ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'