---
- name: Install Docker
  hosts: 192.168.1.88
  become: true

  handlers:
    - name: docker status
      service: name=docker state=started

  tasks:

    - name: Install prerequisite packages
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
          - python3-pip
          - python3-setuptools
          - aptitude

    - name: Install docker and its dependecies
      apt: 
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages: #packages get redefined here
        - docker.io
      notify:
        - docker status

    - name: Disable swap
      command: swapoff -a
      when: ansible_swaptotal_mb > 0
