---
- name: Install Docker
  hosts: 192.168.1.88
  become: true

  handlers:
    - name: docker status
      service: name=docker state=started

  tasks:

    - name: Install prerequisite packages
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
          - python3-pip
          - python3-setuptools
          - aptitude

    - name: Install docker
      apt: 
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages: #packages get redefined here
        - docker.io
      notify:
        - docker status

    - name: Change default cgroups driver
      shell: |
        cat > /etc/docker/daemon.json << EOF
        {
          "exec-opts": ["native.cgroupdriver=systemd"],
          "log-driver": "json-file",
          "log-opts": {
            "max-size": "100m"
          },
          "storage-driver": "overlay2"
        }
        EOF
      args:
        chdir: /etc/docker
        creates: daemon.json
        executable: /bin/bash

    - name: Enable cgroups limit support
      lineinfile:
        path: /boot/firmware/cmdline.txt
        state: present
        backrefs: yes
        regexp: 'quiet splash$'
        line: 'dwc_otg.lpm_enable=0 console=serial0,115200 console=tty1 root=LABEL=writable rootfstype=ext4 elevator=deadline rootwait fixrtc quiet splash cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1 swapaccount=1/'        